### ISSUE TITLE
remove white box from bottom of the page

### ISSUE THREAD

**Issue by eriledup** [EmilyLopez-Ichikawa/Love-Letters#3]
remove the white box that appears when the user manually scrolls to the bottom of the page. The div "blockColorblindContent" appears to be the culprit of the white space. 

<img width="1552" alt="Screen Shot 2021-02-04 at 11 01 10 PM" src="https://user-images.githubusercontent.com/78395947/106991920-e30e5c80-673c-11eb-9d72-b927a8fa254c.png">

<img width="1552" alt="Screen Shot 2021-02-04 at 11 02 34 PM" src="https://user-images.githubusercontent.com/78395947/106992054-308ac980-673d-11eb-935c-f98f680956e5.png">

<img width="1552" alt="Screen Shot 2021-02-04 at 11 03 06 PM" src="https://user-images.githubusercontent.com/78395947/106992065-35e81400-673d-11eb-9568-8a4519696188.png">

**Comment by EmilyLopez-Ichikawa** [comment]
Determined that this is due to one of Emma's Chrome extensions - not an issue we'll be dealing with
